version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mv target/server-1.0.jar application.jar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - application.jar
    - .platform/**/*
cache:
  paths:
    - '/root/.m2/**/*'
